// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'code': string;
  'container': string;
  'emoji': string;
  'howto': string;
  'inner': string;
  'input': string;
  'item': string;
  'item-null': string;
  'itemNull': string;
  'left': string;
  'lister': string;
  'middle': string;
  'right': string;
  'themedark': string;
  'themelight': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
